name: Build Notebook
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade jupytext papermill
      - run: jupytext --to ipynb Fraud_notebook.py
      - run: papermill Fraud_notebook.ipynb Fraud_notebook.executed.ipynb
      - name: Commit executed notebook
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add Fraud_notebook.ipynb Fraud_notebook.executed.ipynb
          git commit -m "CI: update executed notebook" || echo "No changes"
          git push
